# Generated by Django 4.1.7 on 2023-02-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=50)),
                ('slug', models.SlugField()),
            ],
            options={
                'db_table': 'categories',
            },
        ),
    ]
