# Generated by Django 4.1.7 on 2023-02-23 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
    ]
